services:
  - type: web
    name: neurobot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn Backend.app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
